server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://my-rds-instance.cqvjqu0ppwf2.ap-northeast-2.rds.amazonaws.com:3306 # url에는 rds의 엔드포인트를 삽입
    username: root
    password: yumiyumi43
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
    # application과 secret은 gitignore에 추가, 보안에 민감하기 때문